import type { VoiceBrainApi, AppSettings } from './useApi';

const defaultSettings: AppSettings = {
  setupComplete: true,
  watchDir: '',
  autoProcessWatchDir: true,
  outputDir: '',
  llamaServerPort: 0,
  llamaEmbedPort: 0,
  localLlmModel: '',
  localEmbedModel: '',
  whisperModel: 'sensevoice',
  llmModel: 'qwen3.5:4b',
  embedModel: 'bge-m3',
  hfToken: '',
  llmProvider: 'local',
  cloudApiUrl: '',
  cloudApiKey: '',
  cloudModel: '',
  cloudEmbedModel: '',
  cloudPresetId: '',
  cloudProviderConfigs: {},
  language: 'en',
  userNickname: '',
  autoReportDaily: false,
  autoReportDailyTime: '22:00',
  autoReportWeekly: false,
  autoReportWeeklyDay: 5,
  autoReportWeeklyTime: '22:00',
  autoReportMonthly: false,
  autoReportMonthlyDay: 1,
  autoReportMonthlyTime: '22:00',
  obsidianVaultDir: '',
  obsidianAutoExport: false,
  obsidianWikilinks: true,
  sceneShortcuts: {
    dictation: 'Alt+,',
    local_meeting: 'CommandOrControl+Shift+L',
    online_meeting: 'CommandOrControl+Shift+M',
    media: 'CommandOrControl+Shift+K',
  },
  autoPasteAfterRecording: true,
  clipboardContinuous: true,
  llmCleanBeforePaste: true,
  llmCleanPrompt: '',
  hotwords: [],
  feishuAppId: '',
  feishuAppSecret: '',
  feishuEnabled: false,
  feishuNotifyOnComplete: true,
  feishuNotifyDailyDigest: false,
  feishuAdminOpenId: '',
  feishuCliEnabled: false,
  feishuCliInstallPath: '',
  feishuCliLastStatus: '',
  feishuCliSyncScopes: 'calendar,task,doc',
  feishuCliLastSyncAt: '',
  wechatCorpId: '',
  wechatAgentId: '',
  wechatSecret: '',
  wechatEnabled: false,
  telegramBotToken: '',
  telegramChatId: '',
  telegramEnabled: false,
  dingtalkAppKey: '',
  dingtalkAppSecret: '',
  dingtalkRobotCode: '',
  dingtalkEnabled: false,
  wechatToken: '',
  wechatEncodingAESKey: '',
  showAllFeatures: false,
  soulConfig: '',
  agentsRules: '',
  streamingModel: 'base',
  workflowTodoPush: true,
  workflowDecisionPush: true,
  workflowUrgentPush: true,
  smtpHost: '',
  smtpPort: 587,
  smtpUser: '',
  smtpPass: '',
  smtpFromName: 'DeepSeno',
  emailEnabled: false,
  plugins: [],
};

/**
 * Creates a mock VoiceBrainApi for development without Electron.
 * All methods return sensible no-op defaults.
 */
export function createMockApi(): VoiceBrainApi {
  return {
    openFile: async () => null,
    selectDirectory: async () => null,
    enqueue: async (_filePath: string) => ({ id: 'mock', status: 'pending' }),
    getQueue: async () => [],
    cancelTask: async () => false,
    retryTask: async () => false,
    pauseQueue: async () => {},
    resumeQueue: async () => {},
    isQueuePaused: async () => false,
    resetStuckTasks: async () => ({ queueCount: 0, dbCount: 0 }),
    reprocessRecording: async () => ({ ok: false, error: 'mock' }),
    getRecordings: async () => [],
    getSegmentsByRecording: async () => [],
    searchSegments: async () => [],
    getMeetingNotes: async () => null,
    regenerateMeetingNotes: async () => ({ error: 'mock' }),
    deleteRecording: async () => ({ success: true }),
    clearAllData: async () => {},
    getExtractedItems: async () => [],
    getAllExtractedItems: async () => [],
    createExtractedItem: async () => null,
    updateExtractedItemStatus: async () => {},
    updateExtractedItem: async () => {},
    deleteExtractedItem: async () => {},
    getDbStats: async () => ({ recordingCount: 0, segmentCount: 0, dbSize: 0 }),
    toggleBookmark: async () => ({ success: true, bookmarked: false }),
    getBookmarkedSegments: async () => [],
    getDashboardCharts: async () => ({ recordingsPerDay: [], sentimentDistribution: [], topSpeakers: [], calendarActivity: [] }),
    getDailySummary: async () => null,
    getSegmentsByDate: async () => [],
    getTextNotes: async () => [],
    getTextNoteById: async () => null,
    generateDailySummary: async () => ({ error: 'mock' }),
    generateWeeklySummary: async () => ({ error: 'mock' }),
    getAllDailySummaries: async () => [],
    deleteDailySummary: async () => ({ success: true }),
    updateDailySummaryKeyEvents: async () => ({ success: true }),
    getAllWeeklySummaries: async () => [],
    deleteWeeklySummary: async () => ({ success: true }),
    generateMonthlySummary: async () => ({ error: 'mock' }),
    getAllMonthlySummaries: async () => [],
    deleteMonthlySummary: async () => ({ success: true }),
    exportDailySummary: async () => ({ error: 'mock' }),
    exportTranscript: async () => ({ error: 'mock' }),
    exportWeeklySummary: async () => ({ error: 'mock' }),
    exportMonthlySummary: async () => ({ error: 'mock' }),
    exportMeetingNotes: async () => ({ error: 'mock' }),
    obsidianSyncAll: async () => ({ success: true, count: 0 }),
    obsidianSyncFile: async () => ({ success: true }),
    getAudioPath: async () => null,
    createSession: async () => ({ success: true, id: 1 }),
    getSessions: async () => [],
    renameSession: async () => ({ success: true }),
    deleteSession: async () => ({ success: true }),
    getSessionMessages: async () => [],
    getChannelSessions: async () => [],
    getChannelSessionMessages: async () => [],
    saveChatMessage: async () => ({ success: true, id: 0 }),
    clearChatMessages: async () => ({ success: true }),
    deleteChatMessage: async () => ({ success: true }),
    getRecordingChatMessages: async () => [],
    clearRecordingChatMessages: async () => ({ success: true }),
    deleteRecordingChatMessage: async () => ({ success: true }),
    ragQuery: async () => ({ answer: '', sources: [] }),
    ragQueryStream: async () => ({ success: false }),
    ragCancelStream: async () => {},
    onRagStreamChunk: () => () => {},
    onRagStreamDone: () => () => {},
    onRagStreamError: () => () => {},
    onRagStreamStatus: () => () => {},
    ragScopedQueryStream: async () => ({ success: false }),
    onRagScopedChunk: () => () => {},
    onRagScopedDone: () => () => {},
    onRagScopedError: () => () => {},
    onRagScopedStatus: () => () => {},
    getStatus: async () => ({
      local: false,
      dbReady: false,
      storageUsed: '0 MB',
    }),
    checkCloudApi: async () => ({ ok: false, error: 'Not available in browser' }),
    listCloudModels: async () => [],
    checkScreenPermission: async () => 'unknown',
    loadSettings: async () => defaultSettings,
    updateSettings: async (p) => ({ ...defaultSettings, ...p }),
    detectHardware: async () => ({
      totalMemoryGB: 16,
      freeMemoryGB: 8,
      cpuCores: 8,
      platform: (navigator.platform.includes('Win') ? 'win32' : navigator.platform.includes('Mac') ? 'darwin' : 'linux') as string,
      arch: (navigator.platform.includes('arm') || navigator.platform.includes('aarch64')) ? 'arm64' : 'x64',
      recommendedLlmModel: 'qwen2.5:7b',
      recommendedQuality: 'good' as const,
    }),
    detectEnvironment: async () => ({
      ffmpeg: { status: 'missing' as const },
      local: { status: 'missing' as const },
      sherpaModels: { status: 'missing' as const },
    }),
    listModels: async () => [],
    pullModel: async (m: string) => ({ success: false, model: m }),
    checkSherpaModels: async () => ({ allReady: false, models: [] }),
    downloadSherpaModels: async () => ({ success: false, error: 'mock' }),
    cancelSherpaDownload: async () => {},
    getSherpaDownloadStatus: async () => null,
    openExternal: async () => {},
    openPath: async () => {},
    openLocalModelsDir: async () => {},
    isLocalInstalled: async () => false,
    installLocal: async () => ({ success: false, error: 'mock' }),
    onLocalInstallProgress: () => () => {},
    getDataDir: async () => '/mock/data/dir',
    clipboardWriteText: async () => {},
    checkFFmpeg: async () => ({ ready: false }),
    downloadFFmpeg: async () => ({ success: false, error: 'Not available in browser' }),
    cancelFFmpegDownload: async () => {},
    onFFmpegDownloadProgress: () => () => {},
    onSetupProgress: () => () => {},
    onModelPullProgress: () => () => {},
    onTaskAdded: () => () => {},
    onTaskProgress: () => () => {},
    onTaskCompleted: () => () => {},
    onTaskFailed: () => () => {},
    onShortcutSearch: () => () => {},
    onShortcutSettings: () => () => {},
    toggleRecording: async () => ({ recording: false }),
    updateSceneShortcut: async () => false,
    onRecordingStateChanged: () => () => {},
    onRecordingSaved: () => () => {},
    onRecordingError: () => () => {},
    feishuGetStatus: async () => ({ status: 'disconnected' }),
    feishuTestConnection: async () => ({ success: false, error: 'mock' }),
    feishuRestart: async () => ({ status: 'disconnected' }),
    externalSourcesListProviders: async () => [{ id: 'feishu-cli', displayName: 'Feishu CLI', domains: ['calendar', 'task', 'doc'] }],
    externalSourcesGetStatus: async () => ({ installed: false, installPath: null, configured: false, loggedIn: false, user: null, lastSyncAt: null }),
    externalSourcesSyncNow: async () => ({ ok: true, documents: 0, chunks: 0 }),
    feishuCliGetStatus: async () => ({ installed: false, installPath: null, configured: false, loggedIn: false, user: null, lastSyncAt: null }),
    feishuCliInstall: async () => ({ ok: true }),
    feishuCliInitConfig: async () => ({ ok: true }),
    feishuCliLogin: async () => ({ ok: true }),
    feishuCliPollLogin: async () => ({ ok: true }),
    feishuCliLogout: async () => ({ ok: true }),
    feishuCliSyncNow: async () => ({ ok: true, documents: 0, chunks: 0 }),
    wechatTestConnection: async () => ({ success: false, error: 'mock' }),
    telegramTestConnection: async () => ({ success: false, error: 'mock' }),
    emailTestConnection: async () => ({ success: false, error: 'mock' }),
    syncGetStatus: async () => ({ enabled: false, syncDir: '', machineId: '', readOnly: false, lockHolder: null }),
    syncEnable: async () => ({ success: false, error: 'mock' }),
    syncDisable: async () => ({ success: false, error: 'mock' }),
    syncTryAcquireLock: async () => ({ acquired: false }),
    realtimeStart: async () => ({ success: false, error: 'mock' }),
    realtimeStop: async () => ({ success: false, error: 'mock' }),
    realtimeStatus: async () => ({ recording: false, recordingId: null }),
    onLiveStarted: () => () => {},
    onLiveSegment: () => () => {},
    onLiveStopped: () => () => {},
    onLivePostComplete: () => () => {},
    onLiveError: () => () => {},
    systemAudioListDevices: async () => [],
    systemAudioStart: async () => ({ success: false, error: 'mock' }),
    systemAudioStop: async () => ({ success: false, error: 'mock' }),
    systemAudioStatus: async () => ({ capturing: false }),
    onSystemAudioProgress: () => () => {},
    onSystemAudioStopped: () => () => {},
    licenseGetStatus: async () => ({ licensed: false, trial: { active: true, daysRemaining: 14, firstLaunchTime: Date.now() }, licenseKey: null, tier: 'trial' as const, features: [] }),
    licenseIsPro: async () => false,
    licenseActivate: async () => ({ success: false, error: 'mock' }),
    licenseDeactivate: async () => ({ success: true }),
    onLicenseChanged: () => undefined,
    lanServerGetStatus: async () => ({ running: false, clientCount: 0 }),
    lanServerStart: async () => ({ success: false, error: 'mock' }),
    lanServerStop: async () => ({ success: true }),
    relayGetStatus: async () => ({ enabled: false, status: 'disconnected' as const, paired: false, transportMode: 'none' as const }),
    relayEnable: async () => ({ success: true, status: 'disconnected' }),
    relayGetPairingQR: async () => ({ url: '', expiresAt: 0 }),
    relayUnpair: async () => ({ success: true }),
    relayGetSubscription: async () => ({ state: 'unsubscribed' as const, licenseKey: '', machineId: 'mock-machine' }),
    exportDatabase: async () => ({ success: false, error: 'mock' }),
    llamaStart: async () => ({ success: false, error: 'mock' }),
    llamaStop: async () => ({ success: false, error: 'mock' }),
    llamaStatus: async () => ({ running: false, port: null, pid: null, model: null }),
    checkForUpdate: async () => ({ available: false }),
    downloadUpdate: async () => ({ success: false, error: 'mock' }),
    installUpdate: async () => {},
    onUpdateAvailable: () => () => {},
    onUpdateDownloadProgress: () => () => {},
    onUpdateDownloaded: () => () => {},
    onUpdateInstallFailed: () => () => {},
    bgdownloadGetState: async () => null,
    bgdownloadStart: async () => {},
    bgdownloadCancel: async () => {},
    bgdownloadRestart: async () => {},
    onBgdownloadState: () => () => {},
    pluginGetAll: async () => [],
    pluginInstall: async () => ({ success: false }),
    skillInstallFromDirectory: async () => ({ success: false, error: 'mock' }),
    skillVerifyGithub: async () => ({ ok: false, error: 'mock' }),
    skillInstallFromGithub: async () => ({ success: false, error: 'mock' }),
    pluginInstallFromUrl: async () => ({ success: false, error: 'mock' }),
    pluginInstallFromRemoteSkill: async () => ({ success: false, error: 'mock' }),
    pluginUninstall: async () => ({ success: false }),
    pluginUpdate: async () => ({ success: false, error: 'mock' }),
    pluginEnable: async () => ({ success: false, error: 'mock' }),
    pluginDisable: async () => ({ success: false, error: 'mock' }),
    pluginGetTools: async () => [],
    pluginGetLogs: async () => [],
    pluginClearLogs: async () => ({}),
    pluginCheckUpdate: async () => null,
    pluginUpgrade: async () => ({ success: false, error: 'mock' }),
    pluginGetMarket: async () => [],
    agentChat: async () => ({ success: false, error: 'mock' }),
    agentChatWithPlugin: async () => ({ success: false, error: 'mock' }),
    schedulerCreate: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerUpdate: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerDelete: async () => ({ success: true }),
    schedulerList: async () => [],
    schedulerGet: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerPause: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'paused', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerResume: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerRunNow: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerHistory: async () => [],
    schedulerParseSchedule: async () => ({ type: 'cron' as const, expr: '0 9 * * *', display: 'mock', nextRunAt: null }),
    schedulerListActions: async () => [],
    memoryGetAll: async () => [],
    memoryGetStats: async () => ({ core: 0, active: 0, archive: 0 }),
    memoryPromote: async () => ({ success: true }),
    memoryDelete: async () => ({ success: true }),
    memoryUpdate: async () => ({ success: true }),
    memoryGetDocumentDates: async () => [],
    memoryGetDocument: async () => null,
    memorySaveDocument: async () => ({ success: true }),
    memoryGenerateDocument: async () => ({ content: '' }),

    // Knowledge Pages
    knowledgeCreate: async () => ({ id: 1, slug: 'test', existed: false }),
    knowledgeGetBySlug: async () => null,
    knowledgeGetAll: async () => [],
    knowledgeUpdateContent: async () => ({ success: true }),
  };
}
