import type { VoiceBrainApi, AppSettings } from './useApi';

const defaultSettings: AppSettings = {
  setupComplete: true,
  watchDir: '',
  autoProcessWatchDir: true,
  outputDir: '',
  llamaServerPort: 0,
  llamaEmbedPort: 0,
  localLlmModel: '',
  localEmbedModel: '',
  whisperModel: 'sensevoice',
  llmModel: 'qwen3.5:4b',
  embedModel: 'bge-m3',
  hfToken: '',
  llmProvider: 'local',
  cloudApiUrl: '',
  cloudApiKey: '',
  cloudModel: '',
  cloudEmbedModel: '',
  cloudPresetId: '',
  cloudProviderConfigs: {},
  language: 'en',
  userNickname: '',
  asrLanguage: 'auto',
  realtimeDailySummary: false,
  autoReportDaily: false,
  autoReportDailyTime: '22:00',
  autoReportWeekly: false,
  autoReportWeeklyDay: 5,
  autoReportWeeklyTime: '22:00',
  autoReportMonthly: false,
  autoReportMonthlyDay: 1,
  autoReportMonthlyTime: '22:00',
  obsidianVaultDir: '',
  obsidianAutoExport: false,
  obsidianWikilinks: true,
  sceneShortcuts: {
    dictation: 'CommandOrControl+Shift+D',
    local_meeting: 'CommandOrControl+Shift+L',
    online_meeting: 'CommandOrControl+Shift+M',
    media: 'CommandOrControl+Shift+K',
  },
  autoPasteAfterRecording: true,
  clipboardContinuous: true,
  llmCleanBeforePaste: true,
  llmCleanPrompt: '',
  hotwords: [],
  feishuAppId: '',
  feishuAppSecret: '',
  feishuEnabled: false,
  feishuNotifyOnComplete: true,
  feishuNotifyDailyDigest: false,
  feishuAdminOpenId: '',
  feishuCliEnabled: false,
  feishuCliInstallPath: '',
  feishuCliLastStatus: '',
  feishuCliSyncScopes: 'calendar,task,doc',
  feishuCliLastSyncAt: '',
  wechatCorpId: '',
  wechatAgentId: '',
  wechatSecret: '',
  wechatEnabled: false,
  telegramBotToken: '',
  telegramChatId: '',
  telegramEnabled: false,
  dingtalkAppKey: '',
  dingtalkAppSecret: '',
  dingtalkRobotCode: '',
  dingtalkEnabled: false,
  openclawWechatEnabled: false,
  wechatToken: '',
  wechatEncodingAESKey: '',
  notificationSound: true,
  showAllFeatures: false,
  soulConfig: '',
  agentsRules: '',
  vocabularyContext: '',
  streamingModel: 'base',
  pasteCleanModel: '',
  workflowTodoPush: true,
  workflowDecisionPush: true,
  workflowUrgentPush: true,
  smtpHost: '',
  smtpPort: 587,
  smtpUser: '',
  smtpPass: '',
  smtpFromName: 'DeepSeno',
  emailRecipient: '',
  emailEnabled: false,
  firstLaunchTime: 0,
  licensing: 'free',
  licenseKey: '',
  diarizationMethod: 'embedding',
  relayTunnelEnabled: false,
  pipelinePrompts: {
    textClean: '',
    imageAnalysis: '',
    videoAnalysis: '',
    infoExtract: '',
    dailySummary: '',
    classify: '',
    memoryExtract: '',
    speakerCorrection: '',
  },
  plugins: [],
};

/**
 * Creates a mock VoiceBrainApi for development without Electron.
 * All methods return sensible no-op defaults.
 */
export function createMockApi(): VoiceBrainApi {
  return {
    openFile: async () => null,
    openFiles: async () => [],
    selectDirectory: async () => null,
    enqueue: async (_filePath: string) => ({ id: 'mock', status: 'pending' }),
    getQueue: async () => [],
    cancelTask: async () => false,
    retryTask: async () => false,
    pauseQueue: async () => {},
    resumeQueue: async () => {},
    isQueuePaused: async () => false,
    resetStuckTasks: async () => ({ queueCount: 0, dbCount: 0 }),
    reprocessRecording: async () => ({ ok: false, error: 'mock' }),
    reoptimizeRecording: async () => ({ ok: false, error: 'mock' }),
    getRecordings: async () => [],
    getSegmentsByRecording: async () => [],
    searchSegments: async () => [],
    getMeetingNotes: async () => null,
    regenerateMeetingNotes: async () => ({ error: 'mock' }),
    backfillTitles: async () => ({ scanned: 0, generated: 0, failed: 0 }),
    backfillCuration: async () => ({ scanned: 0, scored: 0, sessioned: 0, failed: 0 }),
    finalizeStaleSessions: async () => ({ stale: 0, finalized: 0 }),
    getTodayCuratedItems: async () => ({ sessions: [], standalones: [], briefs: [] }),
    updateRecordingTitle: async () => ({ success: true }),
    updateRecordingCategory: async () => ({ success: true }),
    updateSegmentText: async () => ({ success: true }),
    deleteRecording: async () => ({ success: true }),
    clearAllData: async () => {},
    getExtractedItems: async () => [],
    getAllExtractedItems: async () => [],
    createExtractedItem: async () => null,
    updateExtractedItemStatus: async () => {},
    updateExtractedItem: async () => {},
    deleteExtractedItem: async () => {},
    getDbStats: async () => ({ recordingCount: 0, segmentCount: 0, dbSize: 0 }),
    toggleBookmark: async () => ({ success: true, bookmarked: false }),
    getBookmarkedSegments: async () => [],
    getDashboardCharts: async () => ({ recordingsPerDay: [], sentimentDistribution: [], topSpeakers: [], calendarActivity: [] }),
    getDailySummary: async () => null,
    getSegmentsByDate: async () => [],
    getTextNotes: async () => [],
    getTextNoteById: async () => null,
    getPersons: async () => [],
    getPerson: async () => null,
    createPerson: async (data) => ({
      id: 0,
      name: data.name,
      type: data.type || 'human',
      notes: data.notes || null,
      created_at: '',
      updated_at: '',
      segment_count: 0,
      total_duration: 0,
    }),
    updatePerson: async (id, data) => ({
      id,
      name: data.name || '',
      type: 'human',
      notes: null,
      created_at: '',
      updated_at: '',
      segment_count: 0,
      total_duration: 0,
    }),
    deletePerson: async () => ({ success: true }),
    mergePersons: async () => ({ success: true }),
    getPersonIdentifiers: async () => [],
    addPersonIdentifier: async (data) => ({
      id: 0,
      person_id: data.person_id,
      type: data.type,
      value: data.value,
      confidence: data.confidence ?? 1,
      source: null,
      created_at: '',
    }),
    deletePersonIdentifier: async () => ({ success: true }),
    getContentByPerson: async () => [],
    getPersonRelationships: async () => [],
    getAllPersonRelationships: async () => [],
    getPersonCoOccurrences: async () => [],
    getPersonSample: async () => null,
    generateDailySummary: async () => ({
      id: 0,
      date: new Date().toISOString().slice(0, 10),
      summary_text: null,
      timeline_json: null,
      key_events_json: null,
      error: 'mock',
    }),
    generateWeeklySummary: async () => ({ error: 'mock' }),
    getAllDailySummaries: async () => [],
    deleteDailySummary: async () => ({ success: true }),
    updateDailySummaryKeyEvents: async () => ({ success: true }),
    getAllWeeklySummaries: async () => [],
    deleteWeeklySummary: async () => ({ success: true }),
    generateMonthlySummary: async () => ({ error: 'mock' }),
    getAllMonthlySummaries: async () => [],
    deleteMonthlySummary: async () => ({ success: true }),
    exportDailySummary: async () => ({ error: 'mock' }),
    exportTranscript: async () => ({ error: 'mock' }),
    exportWeeklySummary: async () => ({ error: 'mock' }),
    exportMonthlySummary: async () => ({ error: 'mock' }),
    exportMeetingNotes: async () => ({ error: 'mock' }),
    obsidianSyncAll: async () => ({ success: true, count: 0 }),
    obsidianSyncFile: async () => ({ success: true }),
    getAudioPath: async () => null,
    createSession: async () => ({ success: true, id: 1 }),
    getSessions: async () => [],
    renameSession: async () => ({ success: true }),
    deleteSession: async () => ({ success: true }),
    getSessionMessages: async () => [],
    getChannelSessions: async () => [],
    getChannelSessionMessages: async () => [],
    saveChatMessage: async () => ({ success: true, id: 0 }),
    clearChatMessages: async () => ({ success: true }),
    deleteChatMessage: async () => ({ success: true }),
    getRecordingChatMessages: async () => [],
    clearRecordingChatMessages: async () => ({ success: true }),
    deleteRecordingChatMessage: async () => ({ success: true }),
    ragQuery: async () => ({ answer: '', sources: [] }),
    ragQueryStream: async () => ({ success: false }),
    ragCancelStream: async () => {},
    getActiveRagStream: async () => null,
    onRagStreamChunk: () => () => {},
    onRagStreamDone: () => () => {},
    onRagStreamError: () => () => {},
    onRagStreamStatus: () => () => {},
    ragScopedQueryStream: async () => ({ success: false }),
    ragCancelScopedStream: async () => {},
    getActiveScopedRagStream: async () => null,
    onRagScopedChunk: () => () => {},
    onRagScopedDone: () => () => {},
    onRagScopedError: () => () => {},
    onRagScopedStatus: () => () => {},
    openDevTools: async () => {},
    getMainLogs: async () => [],
    onMainLog: () => () => {},
    getStatus: async () => ({
      local: false,
      dbReady: false,
      storageUsed: '0 MB',
    }),
    checkCloudApi: async (_url?: string, _apiKey?: string, _model?: string) => ({ ok: false, error: 'Not available in browser' }),
    listCloudModels: async () => [],
    checkScreenPermission: async () => 'unknown',
    loadSettings: async () => defaultSettings,
    updateSettings: async (p) => ({ ...defaultSettings, ...p }),
    detectHardware: async () => ({
      totalMemoryGB: 16,
      freeMemoryGB: 8,
      cpuCores: 8,
      platform: (navigator.platform.includes('Win') ? 'win32' : navigator.platform.includes('Mac') ? 'darwin' : 'linux') as string,
      arch: (navigator.platform.includes('arm') || navigator.platform.includes('aarch64')) ? 'arm64' : 'x64',
      recommendedLlmModel: 'qwen2.5:7b',
      recommendedQuality: 'good' as const,
    }),
    getDefaultPrompts: async () => defaultSettings.pipelinePrompts,
    detectEnvironment: async () => ({
      ffmpeg: { status: 'missing' as const },
      local: { status: 'missing' as const },
      sherpaModels: { status: 'missing' as const },
    }),
    listModels: async () => [],
    pullModel: async (m: string) => ({ success: false, model: m }),
    testLocal: async () => ({ success: false, error: 'mock' }),
    cancelPull: async () => {},
    getPullStatus: async () => [],
    checkSherpaModels: async () => ({ allReady: false, models: [] }),
    downloadSherpaModels: async () => ({ success: false, error: 'mock' }),
    cancelSherpaDownload: async () => {},
    getSherpaDownloadStatus: async () => null,
    openExternal: async () => {},
    openPath: async () => {},
    openLocalModelsDir: async () => {},
    isLocalInstalled: async () => false,
    installLocal: async () => ({ success: false, error: 'mock' }),
    onLocalInstallProgress: () => () => {},
    getDataDir: async () => '/mock/data/dir',
    clipboardWriteText: async () => {},
    getPathForFile: () => '',
    checkFFmpeg: async () => ({ ready: false }),
    downloadFFmpeg: async () => ({ success: false, error: 'Not available in browser' }),
    cancelFFmpegDownload: async () => {},
    onFFmpegDownloadProgress: () => () => {},
    onSetupProgress: () => () => {},
    onModelPullProgress: () => () => {},
    onTaskAdded: () => () => {},
    onTaskProgress: () => () => {},
    onTaskCompleted: () => () => {},
    onTaskCancelled: () => () => {},
    onTextNoteNew: () => () => {},
    onTaskFailed: () => () => {},
    onShortcutSearch: () => () => {},
    onShortcutSettings: () => () => {},
    toggleRecording: async () => ({ recording: false }),
    updateSceneShortcut: async () => false,
    onRecordingStateChanged: () => () => {},
    onRecordingSaved: () => () => {},
    onRecordingError: () => () => {},
    onPostProcessing: () => () => {},
    onPostProcessComplete: () => () => {},
    feishuGetStatus: async () => ({ status: 'disconnected' }),
    feishuTestConnection: async () => ({ success: false, error: 'mock' }),
    feishuRestart: async () => ({ status: 'disconnected' }),
    feishuSimulate: async () => ({ success: false, error: 'mock' }),
    feishuRunTestSuite: async () => ({ success: false, error: 'mock' }),
    externalSourcesListProviders: async () => [{ id: 'feishu-cli', displayName: 'Feishu CLI', domains: ['calendar', 'task', 'doc'] }],
    externalSourcesGetStatus: async () => ({ installed: false, installPath: null, configured: false, loggedIn: false, user: null, lastSyncAt: null }),
    externalSourcesSyncNow: async () => ({ ok: true, documents: 0, chunks: 0 }),
    feishuCliGetStatus: async () => ({ installed: false, installPath: null, configured: false, loggedIn: false, user: null, lastSyncAt: null }),
    feishuCliInstall: async () => ({ ok: true }),
    feishuCliInitConfig: async () => ({ ok: true }),
    feishuCliLogin: async () => ({ ok: true }),
    feishuCliPollLogin: async () => ({ ok: true }),
    feishuCliLogout: async () => ({ ok: true }),
    feishuCliSyncNow: async () => ({ ok: true, documents: 0, chunks: 0 }),
    wechatTestConnection: async () => ({ success: false, error: 'mock' }),
    telegramTestConnection: async () => ({ success: false, error: 'mock' }),
    openclawWechatGetQRCode: async () => ({ qrcodeId: '', qrcodeImage: '' }),
    openclawWechatGetQRCodeStatus: async () => ({ status: 'pending' as const }),
    openclawWechatTestConnection: async () => ({ success: false, error: 'mock' }),
    openclawWechatLogout: async () => ({ success: true }),
    openclawWechatGetStatus: async () => ({ status: 'disconnected' as const }),
    emailTestConnection: async () => ({ success: false, error: 'mock' }),
    syncGetStatus: async () => ({ enabled: false, syncDir: '', machineId: '', readOnly: false, lockHolder: null }),
    syncEnable: async () => ({ success: false, error: 'mock' }),
    syncDisable: async () => ({ success: false, error: 'mock' }),
    syncTryAcquireLock: async () => ({ acquired: false }),
    realtimeStart: async () => ({ success: false, error: 'mock' }),
    realtimeStop: async () => ({ success: false, error: 'mock' }),
    realtimeStatus: async () => ({ recording: false, recordingId: null }),
    onLiveStarted: () => () => {},
    onLiveSegment: () => () => {},
    onLiveStopped: () => () => {},
    onLivePostComplete: () => () => {},
    onLiveError: () => () => {},
    systemAudioListDevices: async () => [],
    systemAudioStart: async () => ({ success: false, error: 'mock' }),
    systemAudioStop: async () => ({ success: false, error: 'mock' }),
    systemAudioStatus: async () => ({ capturing: false }),
    onSystemAudioProgress: () => () => {},
    onSystemAudioStopped: () => () => {},
    licenseGetStatus: async () => ({
      licensed: true,
      trial: { active: false, daysRemaining: 0, firstLaunchTime: Date.now() },
      licenseKey: null,
      tier: 'free' as const,
      features: ['recording', 'transcription', 'memory', 'auto_reports', 'channels', 'mobile_sync'],
    }),
    licenseIsPro: async () => true,
    licenseActivate: async () => ({ success: true, tier: 'free' as const }),
    licenseDeactivate: async () => ({ success: true }),
    onLicenseChanged: () => undefined,
    lanServerGetStatus: async () => ({ running: false, clientCount: 0 }),
    lanServerStart: async () => ({ success: false, error: 'mock' }),
    lanServerStop: async () => ({ success: true }),
    relayGetStatus: async () => ({ enabled: false, status: 'disconnected' as const, paired: false, transportMode: 'none' as const }),
    relayEnable: async () => ({ success: true, status: 'disconnected' }),
    relayGetPairingQR: async () => ({ url: '', expiresAt: 0 }),
    relayUnpair: async () => ({ success: true }),
    exportDatabase: async () => ({ success: false, error: 'mock' }),
    llamaStart: async () => ({ success: false, error: 'mock' }),
    llamaStop: async () => ({ success: false, error: 'mock' }),
    llamaStatus: async () => ({ running: false, port: null, pid: null, model: null }),
    checkForUpdate: async () => ({ available: false }),
    downloadUpdate: async () => ({ success: false, error: 'mock' }),
    installUpdate: async () => {},
    onUpdateAvailable: () => () => {},
    onUpdateDownloadProgress: () => () => {},
    onUpdateDownloaded: () => () => {},
    onUpdateInstallFailed: () => () => {},
    bgdownloadGetState: async () => null,
    bgdownloadStart: async () => {},
    bgdownloadCancel: async () => {},
    bgdownloadRestart: async () => {},
    onBgdownloadState: () => () => {},
    pluginGetAll: async () => [],
    pluginInstall: async () => ({ success: false }),
    skillInstallFromDirectory: async () => ({ success: false, error: 'mock' }),
    skillVerifyGithub: async () => ({ ok: false, error: 'mock' }),
    skillInstallFromGithub: async () => ({ success: false, error: 'mock' }),
    pluginInstallFromUrl: async () => ({ success: false, error: 'mock' }),
    pluginInstallFromRemoteSkill: async () => ({ success: false, error: 'mock' }),
    pluginUninstall: async () => ({ success: false }),
    pluginUpdate: async () => ({ success: false, error: 'mock' }),
    pluginEnable: async () => ({ success: false, error: 'mock' }),
    pluginDisable: async () => ({ success: false, error: 'mock' }),
    pluginGetTools: async () => [],
    pluginGetLogs: async () => [],
    pluginClearLogs: async () => ({}),
    pluginCheckUpdate: async () => null,
    pluginUpgrade: async () => ({ success: false, error: 'mock' }),
    pluginGetMarket: async () => [],
    agentChat: async () => ({ success: false, error: 'mock' }),
    agentChatWithPlugin: async () => ({ success: false, error: 'mock' }),
    schedulerCreate: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerUpdate: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerDelete: async () => ({ success: true }),
    schedulerList: async () => [],
    schedulerGet: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerPause: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'paused', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerResume: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerRunNow: async () => ({ id: 0, name: '', description: null, task_type: 'custom', action: '', action_params: null, schedule_type: 'cron', schedule_expr: null, schedule_display: null, is_recurring: 1, status: 'active', next_run_at: null, last_run_at: null, last_run_status: null, last_run_result: null, run_count: 0, fail_count: 0, retry_count: 0, permission_level: 'readonly', allowed_tools: null, channels_override: null, missed_policy: 'catch_up_latest', max_miss_hours: 24, max_retries: 1, created_by: 'user', created_at: '', updated_at: '' }),
    schedulerHistory: async () => [],
    schedulerParseSchedule: async () => ({ type: 'cron' as const, expr: '0 9 * * *', display: 'mock', nextRunAt: null }),
    schedulerListActions: async () => [],
    memoryGetAll: async () => [],
    memoryGetStats: async () => ({ core: 0, active: 0, archive: 0 }),
    memoryPromote: async () => ({ success: true }),
    memoryDelete: async () => ({ success: true }),
    memoryUpdate: async () => ({ success: true }),
    memoryGetDocumentDates: async () => [],
    memoryGetDocument: async () => null,
    memorySaveDocument: async () => ({ success: true }),
    memoryGenerateDocument: async () => ({ content: '' }),

    // Knowledge Pages
    knowledgeCreate: async () => ({ id: 1, slug: 'test', existed: false }),
    knowledgeGetBySlug: async () => null,
    knowledgeGetAll: async () => [],
    knowledgeSearch: async () => [],
    knowledgeGetLinks: async () => [],
    knowledgeGetBacklinks: async () => [],
    knowledgeGetGraph: async () => ({ nodes: [], edges: [] }),
    knowledgeGetQueueStatus: async () => ({ pending: 0, processing: 0, failed: 0 }),
    knowledgeGetQueueEntries: async () => [],
    knowledgeClearStuckQueue: async () => ({ success: true }),
    knowledgeGetStats: async () => ({ total: 0, person: 0, topic: 0, project: 0, concept: 0 }),
    knowledgeRecompile: async () => ({ success: true }),
    knowledgeCompileRecording: async () => ({ success: true }),
    knowledgeUpdateContent: async () => ({ success: true }),
    knowledgeCompileAll: async () => ({ success: true }),
    knowledgeMergePages: async () => ({ success: true }),
    knowledgeFindDuplicates: async () => [],
    knowledgeDelete: async () => ({ success: true }),
    knowledgeBatchDelete: async () => ({ success: true }),
    knowledgeRenamePage: async () => ({ success: true }),
    knowledgeEditContent: async () => ({ success: true }),
  };
}
